### ISSUE TITLE
Feature: Need to work on contact page

### ISSUE THREAD

**Issue by SubhPB** [SubhPB/s-portfolio#3]
## New page "Contact"
Here are the features we need in contact page.
# Make pull request only to feat/contact branch.
1) Add Section heading.
2) Add some cool animation with framer motion when comes in the view for first time.
3) create a server action to send email 
4) need submit button as outer component 
5) Add form 
6) Form takes two inputs: [i] input as email [ii] textarea to leaving message

These are the requirements and must be included in final pull request.

**Comment by byimaan** [comment]
Okay!
